spring:
  datasource:
    url: jdbc:h2:mem:maindb
  flyway:
    enabled: true
    locations: classpath:/db/migration
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    generate-ddl: false